name: small-molecule-design
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10
  - pytorch>=1.13.0
  - gemmi>=0.6.4
  - numpy>=1.25.2
  - tqdm>=4.66.1
  - h5py>=3.9.0
  - scikit-learn>=1.7.2
  - scipy>=1.16.3
  - pandas>=2.3.3
